# Generated by Django 5.2.18 on 2026-10-07 03:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('course', models.CharField(blank=True, max_length=255)),
                ('tuition', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('living_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('scholarships', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('family_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('assets', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('collateral_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cibil_score', models.PositiveIntegerField(default=0)),
                ('route', models.CharField(choices=[('collateral', 'Collateral'), ('non_collateral', 'Non-collateral')], default='non_collateral', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('itr', 'ITR'), ('bank_statement', 'Bank statement'), ('salary_slip', 'Salary slip'), ('ca_net_worth', 'CA net worth certificate'), ('property_document', 'Property document'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loan_type', models.CharField(max_length=30)),
                ('interest_rate', models.CharField(max_length=50)),
                ('minimum_cibil', models.PositiveIntegerField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True)),
                ('document_categories', models.JSONField(default=list)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'loan_type'), name='unique_lender_loan_type')],
            },
        ),
    ]
