# Generated by Django 5.2.18 on 2026-10-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='co_applicant_type',
            field=models.CharField(choices=[('salaried', 'Salaried'), ('self_employed', 'Self-employed')], default='salaried', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='property_state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Maharashtra', 'Maharashtra'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('pan_card', 'PAN Card'), ('proof_of_residence', 'Proof of residence (Voter ID / Passport / Electricity Bill / Telephone Bill / Ration Card / Bank account statement / Government Identity Proof)'), ('bank_statement_6m', 'Bank account statement for last 6 months (personal / salary)'), ('asset_liability_statement', 'Personal Asset & Liability Statement'), ('marksheets', '10th, 12th, and Degree marksheets/certificates'), ('admission_proof', 'Proof of admission showing total course duration'), ('fee_structure', 'Fee structure (I-20 for US, if available)'), ('test_scores', 'IELTS / GMAT / GRE score card'), ('university_ranking', 'University ranking print-out'), ('salary_slips_3m', 'Latest salary slips (last 3 months)'), ('form_16_2y', 'Form 16 (last 2 years)'), ('employer_id', 'Employer ID card'), ('itr_2y', 'ITR (last 2 years)'), ('itr_3y', 'ITR (last 3 years)'), ('financial_statements_3y', 'Balance sheet and Profit & Loss account (last 3 years)'), ('business_address_proof', 'Proof of business address'), ('title_deed', 'Property title deed and registered sale agreement'), ('registration_receipt', 'Original registration receipt'), ('municipal_allotment', 'Allotment letter by Municipal Corporation / authorised government authority'), ('encumbrance_cert_30y', 'Previous chain of sale deeds / Encumbrance Certificate (EC) of last 30 years'), ('property_tax_receipt', 'Latest property tax bill or electricity bill with same address'), ('approved_building_plan', 'Municipality-approved building plan or plot layout'), ('occupancy_certificate', 'Occupancy Certificate (OC) (if apartment)'), ('delhi_conveyance_dda', 'Conveyance deed and DDA allotment letter'), ('mh_builder_noc_index2', 'NOC from builder/society with Index II, share certificate, society conveyance deed, POA confirmation, commencement certificate, and board resolution'), ('itr', 'ITR'), ('bank_statement', 'Bank statement'), ('salary_slip', 'Salary slip'), ('ca_net_worth', 'CA net worth certificate'), ('property_document', 'Property document'), ('other', 'Other')], max_length=40),
        ),
    ]
